// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/kvdb.proto

#include "proto/kvdb.pb.h"
#include "proto/kvdb.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace kvdb {

static const char* KVDBService_method_names[] = {
  "/kvdb.KVDBService/Put",
  "/kvdb.KVDBService/Get",
  "/kvdb.KVDBService/Delete",
  "/kvdb.KVDBService/BatchPut",
  "/kvdb.KVDBService/BatchGet",
  "/kvdb.KVDBService/Scan",
  "/kvdb.KVDBService/PrefixScan",
  "/kvdb.KVDBService/CreateSnapshot",
  "/kvdb.KVDBService/ReleaseSnapshot",
  "/kvdb.KVDBService/GetAtSnapshot",
  "/kvdb.KVDBService/Flush",
  "/kvdb.KVDBService/Compact",
  "/kvdb.KVDBService/GetStats",
  "/kvdb.KVDBService/SetCompactionStrategy",
  "/kvdb.KVDBService/Subscribe",
};

std::unique_ptr< KVDBService::Stub> KVDBService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< KVDBService::Stub> stub(new KVDBService::Stub(channel));
  return stub;
}

KVDBService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Put_(KVDBService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Get_(KVDBService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Delete_(KVDBService_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BatchPut_(KVDBService_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BatchGet_(KVDBService_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Scan_(KVDBService_method_names[5], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_PrefixScan_(KVDBService_method_names[6], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_CreateSnapshot_(KVDBService_method_names[7], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReleaseSnapshot_(KVDBService_method_names[8], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetAtSnapshot_(KVDBService_method_names[9], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Flush_(KVDBService_method_names[10], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Compact_(KVDBService_method_names[11], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetStats_(KVDBService_method_names[12], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetCompactionStrategy_(KVDBService_method_names[13], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Subscribe_(KVDBService_method_names[14], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status KVDBService::Stub::Put(::grpc::ClientContext* context, const ::kvdb::PutRequest& request, ::kvdb::PutResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Put_, context, request, response);
}

void KVDBService::Stub::experimental_async::Put(::grpc::ClientContext* context, const ::kvdb::PutRequest* request, ::kvdb::PutResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Put_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::Put(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::PutResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Put_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::Put(::grpc::ClientContext* context, const ::kvdb::PutRequest* request, ::kvdb::PutResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Put_, context, request, response, reactor);
}

void KVDBService::Stub::experimental_async::Put(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::PutResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Put_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kvdb::PutResponse>* KVDBService::Stub::AsyncPutRaw(::grpc::ClientContext* context, const ::kvdb::PutRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::PutResponse>::Create(channel_.get(), cq, rpcmethod_Put_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::kvdb::PutResponse>* KVDBService::Stub::PrepareAsyncPutRaw(::grpc::ClientContext* context, const ::kvdb::PutRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::PutResponse>::Create(channel_.get(), cq, rpcmethod_Put_, context, request, false);
}

::grpc::Status KVDBService::Stub::Get(::grpc::ClientContext* context, const ::kvdb::GetRequest& request, ::kvdb::GetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Get_, context, request, response);
}

void KVDBService::Stub::experimental_async::Get(::grpc::ClientContext* context, const ::kvdb::GetRequest* request, ::kvdb::GetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::Get(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::GetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::Get(::grpc::ClientContext* context, const ::kvdb::GetRequest* request, ::kvdb::GetResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

void KVDBService::Stub::experimental_async::Get(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::GetResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kvdb::GetResponse>* KVDBService::Stub::AsyncGetRaw(::grpc::ClientContext* context, const ::kvdb::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::GetResponse>::Create(channel_.get(), cq, rpcmethod_Get_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::kvdb::GetResponse>* KVDBService::Stub::PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::kvdb::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::GetResponse>::Create(channel_.get(), cq, rpcmethod_Get_, context, request, false);
}

::grpc::Status KVDBService::Stub::Delete(::grpc::ClientContext* context, const ::kvdb::DeleteRequest& request, ::kvdb::DeleteResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Delete_, context, request, response);
}

void KVDBService::Stub::experimental_async::Delete(::grpc::ClientContext* context, const ::kvdb::DeleteRequest* request, ::kvdb::DeleteResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Delete_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::Delete(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::DeleteResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Delete_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::Delete(::grpc::ClientContext* context, const ::kvdb::DeleteRequest* request, ::kvdb::DeleteResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Delete_, context, request, response, reactor);
}

void KVDBService::Stub::experimental_async::Delete(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::DeleteResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Delete_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kvdb::DeleteResponse>* KVDBService::Stub::AsyncDeleteRaw(::grpc::ClientContext* context, const ::kvdb::DeleteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::DeleteResponse>::Create(channel_.get(), cq, rpcmethod_Delete_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::kvdb::DeleteResponse>* KVDBService::Stub::PrepareAsyncDeleteRaw(::grpc::ClientContext* context, const ::kvdb::DeleteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::DeleteResponse>::Create(channel_.get(), cq, rpcmethod_Delete_, context, request, false);
}

::grpc::Status KVDBService::Stub::BatchPut(::grpc::ClientContext* context, const ::kvdb::BatchPutRequest& request, ::kvdb::BatchPutResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_BatchPut_, context, request, response);
}

void KVDBService::Stub::experimental_async::BatchPut(::grpc::ClientContext* context, const ::kvdb::BatchPutRequest* request, ::kvdb::BatchPutResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_BatchPut_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::BatchPut(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::BatchPutResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_BatchPut_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::BatchPut(::grpc::ClientContext* context, const ::kvdb::BatchPutRequest* request, ::kvdb::BatchPutResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_BatchPut_, context, request, response, reactor);
}

void KVDBService::Stub::experimental_async::BatchPut(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::BatchPutResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_BatchPut_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kvdb::BatchPutResponse>* KVDBService::Stub::AsyncBatchPutRaw(::grpc::ClientContext* context, const ::kvdb::BatchPutRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::BatchPutResponse>::Create(channel_.get(), cq, rpcmethod_BatchPut_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::kvdb::BatchPutResponse>* KVDBService::Stub::PrepareAsyncBatchPutRaw(::grpc::ClientContext* context, const ::kvdb::BatchPutRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::BatchPutResponse>::Create(channel_.get(), cq, rpcmethod_BatchPut_, context, request, false);
}

::grpc::Status KVDBService::Stub::BatchGet(::grpc::ClientContext* context, const ::kvdb::BatchGetRequest& request, ::kvdb::BatchGetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_BatchGet_, context, request, response);
}

void KVDBService::Stub::experimental_async::BatchGet(::grpc::ClientContext* context, const ::kvdb::BatchGetRequest* request, ::kvdb::BatchGetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_BatchGet_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::BatchGet(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::BatchGetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_BatchGet_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::BatchGet(::grpc::ClientContext* context, const ::kvdb::BatchGetRequest* request, ::kvdb::BatchGetResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_BatchGet_, context, request, response, reactor);
}

void KVDBService::Stub::experimental_async::BatchGet(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::BatchGetResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_BatchGet_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kvdb::BatchGetResponse>* KVDBService::Stub::AsyncBatchGetRaw(::grpc::ClientContext* context, const ::kvdb::BatchGetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::BatchGetResponse>::Create(channel_.get(), cq, rpcmethod_BatchGet_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::kvdb::BatchGetResponse>* KVDBService::Stub::PrepareAsyncBatchGetRaw(::grpc::ClientContext* context, const ::kvdb::BatchGetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::BatchGetResponse>::Create(channel_.get(), cq, rpcmethod_BatchGet_, context, request, false);
}

::grpc::ClientReader< ::kvdb::ScanResponse>* KVDBService::Stub::ScanRaw(::grpc::ClientContext* context, const ::kvdb::ScanRequest& request) {
  return ::grpc_impl::internal::ClientReaderFactory< ::kvdb::ScanResponse>::Create(channel_.get(), rpcmethod_Scan_, context, request);
}

void KVDBService::Stub::experimental_async::Scan(::grpc::ClientContext* context, ::kvdb::ScanRequest* request, ::grpc::experimental::ClientReadReactor< ::kvdb::ScanResponse>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderFactory< ::kvdb::ScanResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_Scan_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::kvdb::ScanResponse>* KVDBService::Stub::AsyncScanRaw(::grpc::ClientContext* context, const ::kvdb::ScanRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::kvdb::ScanResponse>::Create(channel_.get(), cq, rpcmethod_Scan_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::kvdb::ScanResponse>* KVDBService::Stub::PrepareAsyncScanRaw(::grpc::ClientContext* context, const ::kvdb::ScanRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::kvdb::ScanResponse>::Create(channel_.get(), cq, rpcmethod_Scan_, context, request, false, nullptr);
}

::grpc::ClientReader< ::kvdb::PrefixScanResponse>* KVDBService::Stub::PrefixScanRaw(::grpc::ClientContext* context, const ::kvdb::PrefixScanRequest& request) {
  return ::grpc_impl::internal::ClientReaderFactory< ::kvdb::PrefixScanResponse>::Create(channel_.get(), rpcmethod_PrefixScan_, context, request);
}

void KVDBService::Stub::experimental_async::PrefixScan(::grpc::ClientContext* context, ::kvdb::PrefixScanRequest* request, ::grpc::experimental::ClientReadReactor< ::kvdb::PrefixScanResponse>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderFactory< ::kvdb::PrefixScanResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_PrefixScan_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::kvdb::PrefixScanResponse>* KVDBService::Stub::AsyncPrefixScanRaw(::grpc::ClientContext* context, const ::kvdb::PrefixScanRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::kvdb::PrefixScanResponse>::Create(channel_.get(), cq, rpcmethod_PrefixScan_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::kvdb::PrefixScanResponse>* KVDBService::Stub::PrepareAsyncPrefixScanRaw(::grpc::ClientContext* context, const ::kvdb::PrefixScanRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::kvdb::PrefixScanResponse>::Create(channel_.get(), cq, rpcmethod_PrefixScan_, context, request, false, nullptr);
}

::grpc::Status KVDBService::Stub::CreateSnapshot(::grpc::ClientContext* context, const ::kvdb::CreateSnapshotRequest& request, ::kvdb::CreateSnapshotResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CreateSnapshot_, context, request, response);
}

void KVDBService::Stub::experimental_async::CreateSnapshot(::grpc::ClientContext* context, const ::kvdb::CreateSnapshotRequest* request, ::kvdb::CreateSnapshotResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateSnapshot_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::CreateSnapshot(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::CreateSnapshotResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateSnapshot_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::CreateSnapshot(::grpc::ClientContext* context, const ::kvdb::CreateSnapshotRequest* request, ::kvdb::CreateSnapshotResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreateSnapshot_, context, request, response, reactor);
}

void KVDBService::Stub::experimental_async::CreateSnapshot(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::CreateSnapshotResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreateSnapshot_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kvdb::CreateSnapshotResponse>* KVDBService::Stub::AsyncCreateSnapshotRaw(::grpc::ClientContext* context, const ::kvdb::CreateSnapshotRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::CreateSnapshotResponse>::Create(channel_.get(), cq, rpcmethod_CreateSnapshot_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::kvdb::CreateSnapshotResponse>* KVDBService::Stub::PrepareAsyncCreateSnapshotRaw(::grpc::ClientContext* context, const ::kvdb::CreateSnapshotRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::CreateSnapshotResponse>::Create(channel_.get(), cq, rpcmethod_CreateSnapshot_, context, request, false);
}

::grpc::Status KVDBService::Stub::ReleaseSnapshot(::grpc::ClientContext* context, const ::kvdb::ReleaseSnapshotRequest& request, ::kvdb::ReleaseSnapshotResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ReleaseSnapshot_, context, request, response);
}

void KVDBService::Stub::experimental_async::ReleaseSnapshot(::grpc::ClientContext* context, const ::kvdb::ReleaseSnapshotRequest* request, ::kvdb::ReleaseSnapshotResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ReleaseSnapshot_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::ReleaseSnapshot(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::ReleaseSnapshotResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ReleaseSnapshot_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::ReleaseSnapshot(::grpc::ClientContext* context, const ::kvdb::ReleaseSnapshotRequest* request, ::kvdb::ReleaseSnapshotResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ReleaseSnapshot_, context, request, response, reactor);
}

void KVDBService::Stub::experimental_async::ReleaseSnapshot(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::ReleaseSnapshotResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ReleaseSnapshot_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kvdb::ReleaseSnapshotResponse>* KVDBService::Stub::AsyncReleaseSnapshotRaw(::grpc::ClientContext* context, const ::kvdb::ReleaseSnapshotRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::ReleaseSnapshotResponse>::Create(channel_.get(), cq, rpcmethod_ReleaseSnapshot_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::kvdb::ReleaseSnapshotResponse>* KVDBService::Stub::PrepareAsyncReleaseSnapshotRaw(::grpc::ClientContext* context, const ::kvdb::ReleaseSnapshotRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::ReleaseSnapshotResponse>::Create(channel_.get(), cq, rpcmethod_ReleaseSnapshot_, context, request, false);
}

::grpc::Status KVDBService::Stub::GetAtSnapshot(::grpc::ClientContext* context, const ::kvdb::GetAtSnapshotRequest& request, ::kvdb::GetAtSnapshotResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetAtSnapshot_, context, request, response);
}

void KVDBService::Stub::experimental_async::GetAtSnapshot(::grpc::ClientContext* context, const ::kvdb::GetAtSnapshotRequest* request, ::kvdb::GetAtSnapshotResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetAtSnapshot_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::GetAtSnapshot(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::GetAtSnapshotResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetAtSnapshot_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::GetAtSnapshot(::grpc::ClientContext* context, const ::kvdb::GetAtSnapshotRequest* request, ::kvdb::GetAtSnapshotResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetAtSnapshot_, context, request, response, reactor);
}

void KVDBService::Stub::experimental_async::GetAtSnapshot(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::GetAtSnapshotResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetAtSnapshot_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kvdb::GetAtSnapshotResponse>* KVDBService::Stub::AsyncGetAtSnapshotRaw(::grpc::ClientContext* context, const ::kvdb::GetAtSnapshotRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::GetAtSnapshotResponse>::Create(channel_.get(), cq, rpcmethod_GetAtSnapshot_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::kvdb::GetAtSnapshotResponse>* KVDBService::Stub::PrepareAsyncGetAtSnapshotRaw(::grpc::ClientContext* context, const ::kvdb::GetAtSnapshotRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::GetAtSnapshotResponse>::Create(channel_.get(), cq, rpcmethod_GetAtSnapshot_, context, request, false);
}

::grpc::Status KVDBService::Stub::Flush(::grpc::ClientContext* context, const ::kvdb::FlushRequest& request, ::kvdb::FlushResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Flush_, context, request, response);
}

void KVDBService::Stub::experimental_async::Flush(::grpc::ClientContext* context, const ::kvdb::FlushRequest* request, ::kvdb::FlushResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Flush_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::Flush(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::FlushResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Flush_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::Flush(::grpc::ClientContext* context, const ::kvdb::FlushRequest* request, ::kvdb::FlushResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Flush_, context, request, response, reactor);
}

void KVDBService::Stub::experimental_async::Flush(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::FlushResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Flush_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kvdb::FlushResponse>* KVDBService::Stub::AsyncFlushRaw(::grpc::ClientContext* context, const ::kvdb::FlushRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::FlushResponse>::Create(channel_.get(), cq, rpcmethod_Flush_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::kvdb::FlushResponse>* KVDBService::Stub::PrepareAsyncFlushRaw(::grpc::ClientContext* context, const ::kvdb::FlushRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::FlushResponse>::Create(channel_.get(), cq, rpcmethod_Flush_, context, request, false);
}

::grpc::Status KVDBService::Stub::Compact(::grpc::ClientContext* context, const ::kvdb::CompactRequest& request, ::kvdb::CompactResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Compact_, context, request, response);
}

void KVDBService::Stub::experimental_async::Compact(::grpc::ClientContext* context, const ::kvdb::CompactRequest* request, ::kvdb::CompactResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Compact_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::Compact(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::CompactResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Compact_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::Compact(::grpc::ClientContext* context, const ::kvdb::CompactRequest* request, ::kvdb::CompactResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Compact_, context, request, response, reactor);
}

void KVDBService::Stub::experimental_async::Compact(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::CompactResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Compact_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kvdb::CompactResponse>* KVDBService::Stub::AsyncCompactRaw(::grpc::ClientContext* context, const ::kvdb::CompactRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::CompactResponse>::Create(channel_.get(), cq, rpcmethod_Compact_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::kvdb::CompactResponse>* KVDBService::Stub::PrepareAsyncCompactRaw(::grpc::ClientContext* context, const ::kvdb::CompactRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::CompactResponse>::Create(channel_.get(), cq, rpcmethod_Compact_, context, request, false);
}

::grpc::Status KVDBService::Stub::GetStats(::grpc::ClientContext* context, const ::kvdb::GetStatsRequest& request, ::kvdb::GetStatsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetStats_, context, request, response);
}

void KVDBService::Stub::experimental_async::GetStats(::grpc::ClientContext* context, const ::kvdb::GetStatsRequest* request, ::kvdb::GetStatsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetStats_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::GetStats(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::GetStatsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetStats_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::GetStats(::grpc::ClientContext* context, const ::kvdb::GetStatsRequest* request, ::kvdb::GetStatsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetStats_, context, request, response, reactor);
}

void KVDBService::Stub::experimental_async::GetStats(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::GetStatsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetStats_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kvdb::GetStatsResponse>* KVDBService::Stub::AsyncGetStatsRaw(::grpc::ClientContext* context, const ::kvdb::GetStatsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::GetStatsResponse>::Create(channel_.get(), cq, rpcmethod_GetStats_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::kvdb::GetStatsResponse>* KVDBService::Stub::PrepareAsyncGetStatsRaw(::grpc::ClientContext* context, const ::kvdb::GetStatsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::GetStatsResponse>::Create(channel_.get(), cq, rpcmethod_GetStats_, context, request, false);
}

::grpc::Status KVDBService::Stub::SetCompactionStrategy(::grpc::ClientContext* context, const ::kvdb::SetCompactionStrategyRequest& request, ::kvdb::SetCompactionStrategyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SetCompactionStrategy_, context, request, response);
}

void KVDBService::Stub::experimental_async::SetCompactionStrategy(::grpc::ClientContext* context, const ::kvdb::SetCompactionStrategyRequest* request, ::kvdb::SetCompactionStrategyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SetCompactionStrategy_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::SetCompactionStrategy(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::SetCompactionStrategyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SetCompactionStrategy_, context, request, response, std::move(f));
}

void KVDBService::Stub::experimental_async::SetCompactionStrategy(::grpc::ClientContext* context, const ::kvdb::SetCompactionStrategyRequest* request, ::kvdb::SetCompactionStrategyResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SetCompactionStrategy_, context, request, response, reactor);
}

void KVDBService::Stub::experimental_async::SetCompactionStrategy(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvdb::SetCompactionStrategyResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SetCompactionStrategy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kvdb::SetCompactionStrategyResponse>* KVDBService::Stub::AsyncSetCompactionStrategyRaw(::grpc::ClientContext* context, const ::kvdb::SetCompactionStrategyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::SetCompactionStrategyResponse>::Create(channel_.get(), cq, rpcmethod_SetCompactionStrategy_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::kvdb::SetCompactionStrategyResponse>* KVDBService::Stub::PrepareAsyncSetCompactionStrategyRaw(::grpc::ClientContext* context, const ::kvdb::SetCompactionStrategyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvdb::SetCompactionStrategyResponse>::Create(channel_.get(), cq, rpcmethod_SetCompactionStrategy_, context, request, false);
}

::grpc::ClientReader< ::kvdb::SubscribeResponse>* KVDBService::Stub::SubscribeRaw(::grpc::ClientContext* context, const ::kvdb::SubscribeRequest& request) {
  return ::grpc_impl::internal::ClientReaderFactory< ::kvdb::SubscribeResponse>::Create(channel_.get(), rpcmethod_Subscribe_, context, request);
}

void KVDBService::Stub::experimental_async::Subscribe(::grpc::ClientContext* context, ::kvdb::SubscribeRequest* request, ::grpc::experimental::ClientReadReactor< ::kvdb::SubscribeResponse>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderFactory< ::kvdb::SubscribeResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_Subscribe_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::kvdb::SubscribeResponse>* KVDBService::Stub::AsyncSubscribeRaw(::grpc::ClientContext* context, const ::kvdb::SubscribeRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::kvdb::SubscribeResponse>::Create(channel_.get(), cq, rpcmethod_Subscribe_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::kvdb::SubscribeResponse>* KVDBService::Stub::PrepareAsyncSubscribeRaw(::grpc::ClientContext* context, const ::kvdb::SubscribeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::kvdb::SubscribeResponse>::Create(channel_.get(), cq, rpcmethod_Subscribe_, context, request, false, nullptr);
}

KVDBService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVDBService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KVDBService::Service, ::kvdb::PutRequest, ::kvdb::PutResponse>(
          [](KVDBService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kvdb::PutRequest* req,
             ::kvdb::PutResponse* resp) {
               return service->Put(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVDBService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KVDBService::Service, ::kvdb::GetRequest, ::kvdb::GetResponse>(
          [](KVDBService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kvdb::GetRequest* req,
             ::kvdb::GetResponse* resp) {
               return service->Get(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVDBService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KVDBService::Service, ::kvdb::DeleteRequest, ::kvdb::DeleteResponse>(
          [](KVDBService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kvdb::DeleteRequest* req,
             ::kvdb::DeleteResponse* resp) {
               return service->Delete(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVDBService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KVDBService::Service, ::kvdb::BatchPutRequest, ::kvdb::BatchPutResponse>(
          [](KVDBService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kvdb::BatchPutRequest* req,
             ::kvdb::BatchPutResponse* resp) {
               return service->BatchPut(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVDBService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KVDBService::Service, ::kvdb::BatchGetRequest, ::kvdb::BatchGetResponse>(
          [](KVDBService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kvdb::BatchGetRequest* req,
             ::kvdb::BatchGetResponse* resp) {
               return service->BatchGet(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVDBService_method_names[5],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< KVDBService::Service, ::kvdb::ScanRequest, ::kvdb::ScanResponse>(
          [](KVDBService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kvdb::ScanRequest* req,
             ::grpc_impl::ServerWriter<::kvdb::ScanResponse>* writer) {
               return service->Scan(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVDBService_method_names[6],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< KVDBService::Service, ::kvdb::PrefixScanRequest, ::kvdb::PrefixScanResponse>(
          [](KVDBService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kvdb::PrefixScanRequest* req,
             ::grpc_impl::ServerWriter<::kvdb::PrefixScanResponse>* writer) {
               return service->PrefixScan(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVDBService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KVDBService::Service, ::kvdb::CreateSnapshotRequest, ::kvdb::CreateSnapshotResponse>(
          [](KVDBService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kvdb::CreateSnapshotRequest* req,
             ::kvdb::CreateSnapshotResponse* resp) {
               return service->CreateSnapshot(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVDBService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KVDBService::Service, ::kvdb::ReleaseSnapshotRequest, ::kvdb::ReleaseSnapshotResponse>(
          [](KVDBService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kvdb::ReleaseSnapshotRequest* req,
             ::kvdb::ReleaseSnapshotResponse* resp) {
               return service->ReleaseSnapshot(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVDBService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KVDBService::Service, ::kvdb::GetAtSnapshotRequest, ::kvdb::GetAtSnapshotResponse>(
          [](KVDBService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kvdb::GetAtSnapshotRequest* req,
             ::kvdb::GetAtSnapshotResponse* resp) {
               return service->GetAtSnapshot(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVDBService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KVDBService::Service, ::kvdb::FlushRequest, ::kvdb::FlushResponse>(
          [](KVDBService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kvdb::FlushRequest* req,
             ::kvdb::FlushResponse* resp) {
               return service->Flush(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVDBService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KVDBService::Service, ::kvdb::CompactRequest, ::kvdb::CompactResponse>(
          [](KVDBService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kvdb::CompactRequest* req,
             ::kvdb::CompactResponse* resp) {
               return service->Compact(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVDBService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KVDBService::Service, ::kvdb::GetStatsRequest, ::kvdb::GetStatsResponse>(
          [](KVDBService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kvdb::GetStatsRequest* req,
             ::kvdb::GetStatsResponse* resp) {
               return service->GetStats(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVDBService_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KVDBService::Service, ::kvdb::SetCompactionStrategyRequest, ::kvdb::SetCompactionStrategyResponse>(
          [](KVDBService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kvdb::SetCompactionStrategyRequest* req,
             ::kvdb::SetCompactionStrategyResponse* resp) {
               return service->SetCompactionStrategy(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVDBService_method_names[14],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< KVDBService::Service, ::kvdb::SubscribeRequest, ::kvdb::SubscribeResponse>(
          [](KVDBService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kvdb::SubscribeRequest* req,
             ::grpc_impl::ServerWriter<::kvdb::SubscribeResponse>* writer) {
               return service->Subscribe(ctx, req, writer);
             }, this)));
}

KVDBService::Service::~Service() {
}

::grpc::Status KVDBService::Service::Put(::grpc::ServerContext* context, const ::kvdb::PutRequest* request, ::kvdb::PutResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KVDBService::Service::Get(::grpc::ServerContext* context, const ::kvdb::GetRequest* request, ::kvdb::GetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KVDBService::Service::Delete(::grpc::ServerContext* context, const ::kvdb::DeleteRequest* request, ::kvdb::DeleteResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KVDBService::Service::BatchPut(::grpc::ServerContext* context, const ::kvdb::BatchPutRequest* request, ::kvdb::BatchPutResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KVDBService::Service::BatchGet(::grpc::ServerContext* context, const ::kvdb::BatchGetRequest* request, ::kvdb::BatchGetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KVDBService::Service::Scan(::grpc::ServerContext* context, const ::kvdb::ScanRequest* request, ::grpc::ServerWriter< ::kvdb::ScanResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KVDBService::Service::PrefixScan(::grpc::ServerContext* context, const ::kvdb::PrefixScanRequest* request, ::grpc::ServerWriter< ::kvdb::PrefixScanResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KVDBService::Service::CreateSnapshot(::grpc::ServerContext* context, const ::kvdb::CreateSnapshotRequest* request, ::kvdb::CreateSnapshotResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KVDBService::Service::ReleaseSnapshot(::grpc::ServerContext* context, const ::kvdb::ReleaseSnapshotRequest* request, ::kvdb::ReleaseSnapshotResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KVDBService::Service::GetAtSnapshot(::grpc::ServerContext* context, const ::kvdb::GetAtSnapshotRequest* request, ::kvdb::GetAtSnapshotResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KVDBService::Service::Flush(::grpc::ServerContext* context, const ::kvdb::FlushRequest* request, ::kvdb::FlushResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KVDBService::Service::Compact(::grpc::ServerContext* context, const ::kvdb::CompactRequest* request, ::kvdb::CompactResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KVDBService::Service::GetStats(::grpc::ServerContext* context, const ::kvdb::GetStatsRequest* request, ::kvdb::GetStatsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KVDBService::Service::SetCompactionStrategy(::grpc::ServerContext* context, const ::kvdb::SetCompactionStrategyRequest* request, ::kvdb::SetCompactionStrategyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KVDBService::Service::Subscribe(::grpc::ServerContext* context, const ::kvdb::SubscribeRequest* request, ::grpc::ServerWriter< ::kvdb::SubscribeResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace kvdb

